# Generated by Django 3.2.8 on 2022-04-01 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogica', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horae', models.DateTimeField(auto_now_add=True)),
                ('horas', models.DateTimeField(null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.asignatura')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'registros',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('horaInicio', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('fecha', models.CharField(max_length=25)),
                ('asignaturas', models.ManyToManyField(blank=True, related_name='HorarioAsg', to='pedagogica.Asignatura')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
                ('asignaturas', models.ManyToManyField(blank=True, related_name='GrupoAsg', to='pedagogica.Asignatura')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.semestre')),
            ],
            options={
                'verbose_name_plural': 'Grupo',
            },
        ),
    ]
