# Generated by Django 3.2.9 on 2022-03-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
                ('asignaturas', models.ManyToManyField(blank=True, related_name='GruposA', to='pedagogica.Asignatura')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.semestre')),
            ],
            options={
                'verbose_name_plural': 'Grupo',
            },
        ),
    ]
