# Generated by Django 3.2.9 on 2021-12-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipoPersona',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='TiposPersona',
        ),
    ]
