# Generated by Django 3.2.9 on 2022-03-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20220316_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
