# Generated by Django 3.2.9 on 2022-01-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionAmb', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ambitos',
            },
        ),
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Anos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('totalHsTeoricas', models.FloatField()),
                ('totalHsPracticas', models.FloatField()),
                ('total', models.FloatField()),
                ('creditos', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100)),
                ('nom_corto', models.CharField(max_length=100)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ano')),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=200)),
                ('descripcionCompetencia', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Ejes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejes', models.CharField(max_length=100)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.asignatura')),
            ],
            options={
                'verbose_name_plural': 'Ejes',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionPe', models.CharField(max_length=400)),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ambitos')),
            ],
            options={
                'verbose_name_plural': 'Perfil_Egresos',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=100)),
                ('ejes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ejes')),
            ],
            options={
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=400)),
                ('descripcionPEgre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.perfil_egreso')),
                ('pCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.carrera')),
            ],
            options={
                'verbose_name_plural': 'Planes_Estudio',
            },
        ),
        migrations.AddField(
            model_name='ano',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.semestre'),
        ),
        migrations.AddField(
            model_name='ambitos',
            name='aCompetencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.competencias'),
        ),
    ]
