# Generated by Django 3.2.9 on 2021-11-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Anos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('totalHsTeoricas', models.FloatField()),
                ('totalHsPracticas', models.FloatField()),
                ('total', models.FloatField()),
                ('creditos', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Ejes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejes', models.CharField(max_length=100)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.asignatura')),
            ],
            options={
                'verbose_name_plural': 'Ejes',
            },
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=400)),
                ('perfilEgreso', models.CharField(max_length=400)),
                ('carreraAsig', models.CharField(max_length=400)),
                ('recomendacionesMet', models.CharField(max_length=400)),
                ('procedimientosEval', models.CharField(max_length=400)),
                ('procedimientosAcre', models.CharField(max_length=400)),
                ('certificacionEst', models.CharField(max_length=400)),
                ('perfilE', models.CharField(max_length=400)),
                ('complementarias', models.CharField(max_length=400)),
                ('firmas', models.CharField(max_length=100)),
                ('direccionEscuela', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Planes_Estudio',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=100)),
                ('ejes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ejes')),
            ],
            options={
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100)),
                ('nom_corto', models.CharField(max_length=100)),
                ('Plan_Estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.plan_estudio')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.ano')),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.AddField(
            model_name='ano',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogica.semestre'),
        ),
    ]
